name: label-size

on: [pull_request]

jobs:
  label-size:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "size/XS",
              "10": "size/S",
              "30": "size/M",
              "100": "size/L",
              "300": "size/XL",
              "1000": "size/XXL"
            }
